name: rgaas workflow

on: [push]

jobs:
  rgaas-workflow:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CMake config
        run: cmake .

      - name: Clang-Format
        run: find ./rgaas/ ./modules/ -name *.h -o -name *.c | xargs clang-format --dry-run -Werror

      - name: Clang-Tidy
        run: find ./rgaas/ ./modules/ -name *.h -o -name *.c | xargs clang-tidy

      - name: CMake build
        run: cmake --build .

      - name: Valgrind (install)
        run: sudo apt-get install valgrind -y

      - name: Valgrind (run)
        run: chmod +x ./test/valgrind/valgrind.sh && ./test/valgrind/valgrind.sh

      - name: Build unit tests (skipped)
        run: exit 0

      - name: Run unit tests (skipped)
        run: exit 0

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build
